import { Task } from './types';
import { Circle, MessageSquareMore, Play, Music } from 'lucide-react';

export const initialTasks: Task[] = [
  {
    id: '1',
    Icon: Circle,
    title: 'Неоновый киберпанк-город под дождём, вид сверху',
    model: 'Midjourney v6',
    estimatedTime: 30,
    cost: 80,
    status: 'inProgress',
    progress: 64,
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    Icon: Circle,
    title: 'Дрон-облёт горного озера на рассвете, 5 сек',
    model: 'Kling 3.0',
    estimatedTime: 120,
    cost: 150,
    status: 'inProgress',
    progress: 28,
    createdAt: Date.now() - 200000,
  },
  {
    id: '3',
    title: 'Сценарий рекламного ролика для кофейни, 30 секунд',
    Icon: MessageSquareMore,
    model: 'GPT-4o',
    estimatedTime: null,
    cost: 6,
    status: 'queued',
    progress: 0,
    createdAt: Date.now() - 300000,
  },
  {
    id: '4',
    Icon: Play,
    title: 'Минималистичный логотип кофейни, бежевые тона',
    model: 'Flux',
    estimatedTime: 12,
    cost: 80,
    status: 'completed',
    progress: 100,
    createdAt: Date.now() - 400000,
  },
  {
    id: '5',
    Icon: Music,
    title: 'Озвучка приветствия мужским голосом',
    model: 'ElevenLabs',
    estimatedTime: 0,
    cost: 20,
    status: 'error',
    progress: 0,
    createdAt: Date.now() - 50000,
  },
  {
    id: '6',
    Icon: Play,
    title: 'Город будущего ночью, неоновые огни',
    model: 'Runway',
    estimatedTime: 0,
    cost: 6,
    status: 'queued',
    progress: 0,
    createdAt: Date.now() - 150000,
  },
  {
    id: '7',
    Icon: Circle,
    title: 'Постер в стиле ретро-футуризм 80-х',
    model: 'Seedream',
    estimatedTime: 0,
    cost: 10,
    status: 'queued',
    progress: 0,
    createdAt: Date.now() - 250000,
  },
  {
    id: '8',
    Icon: Play,
    title: 'Подводный мир с фантастическими существами',
    model: 'Sora',
    estimatedTime: 0,
    cost: 200,
    status: 'error',
    progress: 0,
    createdAt: Date.now() - 350000,
  },
];